import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { RootState } from "../../app/store";
import { Joke } from "../../types/Joke";
import { fetchJokebox, fetchBonusJoke } from "./jokeboxAPI";

export interface JokeboxState {
	jokes: any[];
	status: "idle" | "loading" | "failed";
}

const initialState: JokeboxState = {
	jokes: [],
	status: "idle",
};

export const fetchJokeboxAsync = createAsyncThunk(
	"jokebox/fetchJokebox",
	async (joke: any) => {
		const response = await fetchJokebox(joke);
		// The value we return becomes the `fulfilled` action payload
		return response.data;
	}
);

export const fetchBonusJokeAsync = createAsyncThunk(
	"jokebox/increment",
	async (joke: Joke) => {
		const response = await fetchBonusJoke(joke);
		// The value we return becomes the `fulfilled` action payload
		return response.data;
	}
);

export const jokeboxSlice = createSlice({
	name: "jokebox",
	initialState,
	// The `reducers` field lets us define reducers and generate associated actions
	reducers: {
		removeLastJoke: (state) => {
			state.jokes.pop();
		},
		changeFavourite: (state, action) => {
			state.jokes[action.payload].favourite =
				!state.jokes[action.payload].favourite;
		},
	},
	// The `extraReducers` field lets the slice handle actions defined elsewhere,
	// including actions generated by createAsyncThunk or in other slices.
	extraReducers: (builder) => {
		builder
			.addCase(fetchJokeboxAsync.pending, (state) => {
				state.status = "loading";
			})
			.addCase(fetchJokeboxAsync.fulfilled, (state, action) => {
				state.status = "idle";
				state.jokes = action.payload;
			})
			.addCase(fetchBonusJokeAsync.pending, (state) => {
				state.status = "loading";
			})
			.addCase(fetchBonusJokeAsync.fulfilled, (state, action) => {
				state.status = "idle";
				state.jokes.push(action.payload);
			});
	},
});

export const { removeLastJoke, changeFavourite } = jokeboxSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.jokebox.value)`
export const selectJokebox = (state: RootState) => state.jokebox;

export default jokeboxSlice.reducer;
